"""empty message

Revision ID: 42d1bdcbf4b3
Revises: ce7be73e459e
Create Date: 2020-09-05 10:43:16.139634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d1bdcbf4b3'
down_revision = 'ce7be73e459e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('other_player', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users_table', 'users_table', ['other_player'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_table', type_='foreignkey')
    op.drop_column('users_table', 'other_player')
    # ### end Alembic commands ###
