"""empty message

Revision ID: 7eed62408abc
Revises: 213efd886acf
Create Date: 2020-08-24 15:05:33.404439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eed62408abc'
down_revision = '213efd886acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_table', 'email')
    # ### end Alembic commands ###
