"""empty message

Revision ID: c6ffc0c72163
Revises: 97b083519fe6
Create Date: 2020-08-26 08:25:11.214072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ffc0c72163'
down_revision = '97b083519fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages_table', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages_table', 'time_created')
    # ### end Alembic commands ###
